AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Lint/SafeNavigationChain:
    Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/TrailingBlankLines:
  EnforcedStyle: final_newline

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Next:
  Enabled: false
